CREATE TABLE CONN_CONF_OBJECT
(
  ID            CHAR(36 BYTE),
  OBJNAME       VARCHAR2(64 BYTE),
  OBJDES        VARCHAR2(64 BYTE),
  OBJTYPE       VARCHAR2(10 BYTE),
  TRANSFERTYPE  CHAR(1 BYTE),
  REMOTESYSTEM  VARCHAR2(64 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN CONN_CONF_OBJECT.ID IS '主键ID';

COMMENT ON COLUMN CONN_CONF_OBJECT.OBJNAME IS '对象名称';

COMMENT ON COLUMN CONN_CONF_OBJECT.OBJDES IS '对象描述';

COMMENT ON COLUMN CONN_CONF_OBJECT.OBJTYPE IS '对象类型';

COMMENT ON COLUMN CONN_CONF_OBJECT.TRANSFERTYPE IS '传输类型';

COMMENT ON COLUMN CONN_CONF_OBJECT.REMOTESYSTEM IS '远程系统';



CREATE TABLE CONN_CONF_TEL
(
  ID            CHAR(36 BYTE),
  TELID         VARCHAR2(10 BYTE),
  TELNAME       VARCHAR2(64 BYTE),
  TRANSFERTYPE  CHAR(1 BYTE),
  QUEUENAME     VARCHAR2(32 BYTE),
  REMOTESYSTEM  VARCHAR2(32 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_CONF_TEL IS '电文配置总表';

COMMENT ON COLUMN CONN_CONF_TEL.ID IS '主键id';

COMMENT ON COLUMN CONN_CONF_TEL.TELID IS '电文ID';

COMMENT ON COLUMN CONN_CONF_TEL.TELNAME IS '电文名称或描述';

COMMENT ON COLUMN CONN_CONF_TEL.TRANSFERTYPE IS '收发类型: S-发送 R-接收';

COMMENT ON COLUMN CONN_CONF_TEL.QUEUENAME IS '【收发类型=S时配置生效】队列名称';

COMMENT ON COLUMN CONN_CONF_TEL.REMOTESYSTEM IS '远程系统名称';



CREATE TABLE CONN_RECV_MAIN
(
  ID        CHAR(36 BYTE),
  TELID     VARCHAR2(10 BYTE),
  TELTYPE   CHAR(2 BYTE),
  MSGID     CHAR(36 BYTE),
  RECVTIME  DATE                                DEFAULT sysdate,
  DEALFLAG  CHAR(1 BYTE)                        DEFAULT '0'
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_RECV_MAIN IS '通信接收总表';

COMMENT ON COLUMN CONN_RECV_MAIN.ID IS '主键';

COMMENT ON COLUMN CONN_RECV_MAIN.TELID IS '电文ID-10位';

COMMENT ON COLUMN CONN_RECV_MAIN.TELTYPE IS '电文类型：SK-socket通信 ，MQ-mq通信';

COMMENT ON COLUMN CONN_RECV_MAIN.MSGID IS '消息ID,对应conn_recv_msg.id';

COMMENT ON COLUMN CONN_RECV_MAIN.RECVTIME IS '接收时间';

COMMENT ON COLUMN CONN_RECV_MAIN.DEALFLAG IS '业务处理标识:0-未处理,1-已处理';



CREATE TABLE CONN_RECV_MAIN_HIS
(
  ID        CHAR(36 BYTE),
  TELID     VARCHAR2(10 BYTE),
  TELTYPE   CHAR(2 BYTE),
  MSGID     CHAR(36 BYTE),
  RECVTIME  DATE,
  DEALFLAG  CHAR(1 BYTE)                        DEFAULT '0',
  DEALTIME  DATE,
  DES       VARCHAR2(255 BYTE),
  ERRCODE   CHAR(4 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_RECV_MAIN_HIS IS '通信接收总表数据归档表';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.ID IS '主键';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.TELID IS '电文ID-10位';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.TELTYPE IS '电文类型：SK-socket通信 ，MQ-mq通信';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.MSGID IS '消息ID,对应conn_recv_msg.id';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.RECVTIME IS '接收时间';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.DEALFLAG IS '业务处理标识:0-未处理,1-已处理';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.DEALTIME IS '业务处理时间';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.DES IS '业务处理备注';

COMMENT ON COLUMN CONN_RECV_MAIN_HIS.ERRCODE IS '错误编号';



CREATE TABLE CONN_RECV_MSG
(
  ID          CHAR(36 BYTE),
  MSGTXT      CLOB,
  CREATETIME  DATE                              DEFAULT sysdate
)
LOB (MSGTXT) STORE AS (
  TABLESPACE USERS
  ENABLE       STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_RECV_MSG IS '通信接收原始数据';

COMMENT ON COLUMN CONN_RECV_MSG.ID IS '消息主键id,对应conn_sk_recv_main.msgId';

COMMENT ON COLUMN CONN_RECV_MSG.MSGTXT IS '接收消息大文本';

COMMENT ON COLUMN CONN_RECV_MSG.CREATETIME IS '记录创建时间';



CREATE TABLE CONN_SEND_MAIN
(
  ID            CHAR(36 BYTE),
  TELID         VARCHAR2(10 BYTE),
  TELTYPE       CHAR(2 BYTE),
  MSGID         CHAR(36 BYTE),
  SENDFLAG      CHAR(1 BYTE)                    DEFAULT '0',
  CREATETIME    DATE                            DEFAULT sysdate,
  PUSHLONGTIME  INTEGER,
  PUSHSEQNO     INTEGER,
  SENDTIME      DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_SEND_MAIN IS '通信发送总表';

COMMENT ON COLUMN CONN_SEND_MAIN.ID IS '主键';

COMMENT ON COLUMN CONN_SEND_MAIN.TELID IS '电文ID-10位';

COMMENT ON COLUMN CONN_SEND_MAIN.TELTYPE IS '电文类型：SK-socket通信 ，MQ-mq通信';

COMMENT ON COLUMN CONN_SEND_MAIN.MSGID IS '消息ID,对应conn_recv_msg.id';

COMMENT ON COLUMN CONN_SEND_MAIN.SENDFLAG IS '发送标识:0-未发送,1-已发送,默认值0';

COMMENT ON COLUMN CONN_SEND_MAIN.CREATETIME IS '记录创建时间';

COMMENT ON COLUMN CONN_SEND_MAIN.PUSHLONGTIME IS '【socket通信使用】推送时间戳';

COMMENT ON COLUMN CONN_SEND_MAIN.PUSHSEQNO IS '【socket通信使用】推送序号-5位循环';

COMMENT ON COLUMN CONN_SEND_MAIN.SENDTIME IS '消息发送时间';



CREATE TABLE CONN_SEND_MAIN_HIS
(
  ID            CHAR(36 BYTE),
  TELID         VARCHAR2(10 BYTE),
  TELTYPE       CHAR(2 BYTE),
  MSGID         CHAR(36 BYTE),
  SENDFLAG      CHAR(1 BYTE),
  SENDRESULT    VARCHAR2(128 BYTE),
  CREATETIME    DATE,
  PUSHLONGTIME  INTEGER,
  PUSHSEQNO     INTEGER,
  SENDTIME      DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_SEND_MAIN_HIS IS '通信发送总表数据归档';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.ID IS '主键id';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.TELID IS '电文ID-10位';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.TELTYPE IS '电文类型：SK-socket通信 ，MQ-mq通信';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.MSGID IS '消息ID';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.SENDFLAG IS '发送标识:0-未发送,1-已发送';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.SENDRESULT IS '发送结果描述';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.CREATETIME IS '记录创建时间';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.PUSHLONGTIME IS '【socket通信使用】推送时间戳';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.PUSHSEQNO IS '【socket通信使用】推送序号-5位循环';

COMMENT ON COLUMN CONN_SEND_MAIN_HIS.SENDTIME IS '消息发送时间';



CREATE TABLE CONN_SEND_MSG
(
  ID          CHAR(36 BYTE),
  MSGTXT      CLOB,
  CREATETIME  DATE                              DEFAULT sysdate
)
LOB (MSGTXT) STORE AS (
  TABLESPACE USERS
  ENABLE       STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_SEND_MSG IS '通信发送原始数据';

COMMENT ON COLUMN CONN_SEND_MSG.ID IS '消息主键id,对应conn_send_main.msgId';

COMMENT ON COLUMN CONN_SEND_MSG.MSGTXT IS '发送消息大文本';

COMMENT ON COLUMN CONN_SEND_MSG.CREATETIME IS '记录创建时间';



CREATE TABLE CONN_TOTAL_NUM
(
  ID        CHAR(36 BYTE),
  TOTALNUM  INTEGER,
  TYPE      CHAR(2 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONN_TOTAL_NUM IS '通信统计表-类型 SS-发送正常,SE-发送失败 RR-接收成功,RE-接收失败';

COMMENT ON COLUMN CONN_TOTAL_NUM.ID IS '主键';

COMMENT ON COLUMN CONN_TOTAL_NUM.TOTALNUM IS '合计数量';

COMMENT ON COLUMN CONN_TOTAL_NUM.TYPE IS '类型 SS-发送正常,SE-发送失败 RR-接收成功,RE-接收失败';



CREATE UNIQUE INDEX CONN_CONF_OBJECT_PK ON CONN_CONF_OBJECT
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_CONF_TEL_PK ON CONN_CONF_TEL
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_RECV_MAIN_HIS_PK ON CONN_RECV_MAIN_HIS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_RECV_MAIN_PK ON CONN_RECV_MAIN
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_RECV_MSG_PK ON CONN_RECV_MSG
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_SEND_MAIN_HIS_PK ON CONN_SEND_MAIN_HIS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_SEND_MAIN_PK ON CONN_SEND_MAIN
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_SEND_MSG_PK ON CONN_SEND_MSG
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONN_TOTAL_NUM_PK ON CONN_TOTAL_NUM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CONN_CONF_OBJECT ADD (
  CONSTRAINT CONN_CONF_OBJECT_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_CONF_OBJECT_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_CONF_TEL ADD (
  CONSTRAINT CONN_CONF_TEL_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_CONF_TEL_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_RECV_MAIN ADD (
  CONSTRAINT CONN_RECV_MAIN_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_RECV_MAIN_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_RECV_MAIN_HIS ADD (
  CONSTRAINT CONN_RECV_MAIN_HIS_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_RECV_MAIN_HIS_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_RECV_MSG ADD (
  CONSTRAINT CONN_RECV_MSG_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_RECV_MSG_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_SEND_MAIN ADD (
  CONSTRAINT CONN_SEND_MAIN_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_SEND_MAIN_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_SEND_MAIN_HIS ADD (
  CONSTRAINT CONN_SEND_MAIN_HIS_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_SEND_MAIN_HIS_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_SEND_MSG ADD (
  CONSTRAINT CONN_SEND_MSG_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_SEND_MSG_PK
  ENABLE VALIDATE);

ALTER TABLE CONN_TOTAL_NUM ADD (
  CONSTRAINT CONN_TOTAL_NUM_PK
  PRIMARY KEY
  (ID)
  USING INDEX CONN_TOTAL_NUM_PK
  ENABLE VALIDATE);
