server:
  port: 8083

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.65:1521:orcl
    username: CONN
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 10000
      read-only: false
  application:
    name: conn-manager-service
system:
  username: admin
  password: connadmin

logging.level.com.suncd.conn.manager.dao: debug
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8


# mvn install:install-file -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0.1.0 -Dpackaging=jar -Dfile=D:\ojdbc6.jar


